export enum StepName {
  CREATE_ORDER = 'CREATE_ORDER',
  RESERVE_INVENTORY = 'RESERVE_INVENTORY',
  CHARGE_PAYMENT = 'CHARGE_PAYMENT',
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
}

export const ALL_STEP_NAMES: StepName[] = [
  StepName.CREATE_ORDER,
  StepName.RESERVE_INVENTORY,
  StepName.CHARGE_PAYMENT,
  StepName.CREATE_SHIPMENT,
];
